Select Id,
   OwnerId,
   IsDeleted,
   Name,
   RecordTypeId,
   CreatedDate,
   CreatedById,
   LastModifiedDate,
   LastModifiedById,
   SystemModstamp,
   Age_in_Hours__c,
   Case_Business_Hours_ID__c,
   Case_Closed__c,
   Case_Created_Date__c,
   Case_Status__c,
   Case__c,
   Current_Time_Included_in_AHT__c,
   Current_Time_Included_in_SLA_Time__c,
   Hours_Excluded_From_SLA__c,
   Hours_Included_in_SLA__c,
   Logged_Hours_Until_First_Handle__c,
   Ultimate_Parent_Case__c,
   Unique_Key__c,
   First_Handle_Time__c,
   Logged_Hours_Excluded_From_SLA__c,
   Logged_Hours_Included_in_AHT__c,
   Logged_Hours_Included_in_SLA__c,
   Most_Recent_Change__c,
   First_Email_Response__c,
   Hours_Until_First_Email_Response__c
From Case_Time__c
Where SystemModStamp >= [START_DATETIME] and SystemModStamp < [END_DATETIME]