SELECT
   ID,
   ISDELETED,
   NAME,
   CREATEDDATE,
   CREATEDBYID,
   LASTMODIFIEDDATE,
   LASTMODIFIEDBYID,
   SYSTEMMODSTAMP,
   LOCALIZATION_REQUEST__C,
   COMPLETED_DATE__C,
   TIME_SPENT_HOURS__C,
   WORDS_COMPLETED__C
FROM LOCALIZATION_TRACKER__C
