SELECT
   ID,
   OWNERID,
   ISDELETED,
   NAME,
   CREATEDDATE,
   CREATEDBYID,
   LASTMODIFIEDDATE,
   LASTMODIFIEDBYID,
   SYSTEMMODSTAMP,
   LASTVIEWEDDATE,
   LASTREFERENCEDDATE,
   ACTIVE__C,
   LOCALIZATION_QUALITY_MANAGER__C
FROM LOCALIZATION_LANGUAGE__C