Select Id,
   OwnerId,
   IsDeleted,
   Name,
   CreatedDate,
   CreatedById,
   LastModifiedDate,
   LastModifiedById,
   SystemModstamp,
   Account__c,
   All_Rounder_Market__c,
   Cases_Closed__c,
   Cases_Created__c,
   Cases_Needed__c,
   Description__c,
   Model__c,
   Recently_Closed_Cases__c,
   Subject__c,
   Time_Completed__c,
   Type__c,
   Age_Days__c,
   Status__c,
   Expedia_Hotel_Id__c
From Onboarding__c