Select Id,
    IsDeleted,
    Name,
    CreatedDate,
    CreatedById,
    LastModifiedDate,
    LastModifiedById,
    SystemModstamp,
    Case_Time__c,
    Case_Owner_Type__c,
    Case_Owner__c,
    Case_Status__c,
    In_Effect_From__c,
    In_Effect_Until__c,
    Included_in_AHT__c,
    Included_in_SLA_Time__c,
    Most_Recent_Change__c,
    New_Case_Owner__c,
    New_Case_Status_Included_in_AHT__c,
    New_Case_Status__c,
    Time_in_Hours__c,
    While_Case_Closed__c,
    While_Closing_Case__c
From Time_Log__c
Where SystemModStamp >= 2016-03-05T00:00:00.000Z and SystemModStamp < 2016-03-05T05:00:00.000Z